# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 10, 141, 61))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(140, 0, 651, 551))
        self.stackedWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(250, 10, 141, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.page1_title_label = QtWidgets.QLabel(self.page_2)
        self.page1_title_label.setGeometry(QtCore.QRect(230, 10, 141, 16))
        self.page1_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.page1_title_label.setObjectName("page1_title_label")
        self.page1_type_label = QtWidgets.QLabel(self.page_2)
        self.page1_type_label.setGeometry(QtCore.QRect(120, 50, 81, 21))
        self.page1_type_label.setObjectName("page1_type_label")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(120, 90, 81, 21))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.page_2)
        self.comboBox.setGeometry(QtCore.QRect(240, 50, 221, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit.setGeometry(QtCore.QRect(240, 90, 221, 21))
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setObjectName("lineEdit")
        self.stackedWidget.addWidget(self.page_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 70, 141, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "本地问答模式"))
        self.label_2.setText(_translate("MainWindow", "哔哩哔哩直播"))
        self.page1_title_label.setText(_translate("MainWindow", "本地问答模式"))
        self.page1_type_label.setText(_translate("MainWindow", "AI问答模式："))
        self.label_4.setText(_translate("MainWindow", "服务器地址："))
        self.comboBox.setItemText(0, _translate("MainWindow", "本地知识库问答"))
        self.comboBox.setItemText(1, _translate("MainWindow", "ChatGLM-普通问答模式"))
        self.lineEdit.setText(_translate("MainWindow", "172.23.0.191"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "请输入服务器地址"))
        self.pushButton_2.setText(_translate("MainWindow", "哔哩哔哩直播"))
